* chapter 3: Protocols
** Why study protocols?
    - they are the rules enforced upon networks that govern how information will be relayed.
** [3.1] The Rules
    - Computer networks use rules to communicate
*** [3.1.2] Communications fundamentals
    - Message source (sender)
      + people or electronic devices that need to send a message to other individuals to other individuals or devices
    - message destination (receiver)
      + receives the message and interprets it
    - Channel
      + consists of the media that provide the pathway over which the message travel from source destination
*** [3.1.3] Communication protocols
    - protocols
      + govern communication over a network
    - two people can communicate through:
      + message source -> tranmitter -> transmission medion -> receiver -> message destination
      + message -> signal -> _________ -> signal -> message
    - before communication, the 'how' to communicate must be agreed upon
      + then, decide the format in which the message will be transmitted
*** [3.1.4] Rule establishment
    - rules that govern the conversation: protocols
    - protocols must account for the following requirements to successfully deliver a message that is understood by the receiver
      + indentified sender and receiver
      + common language and grammar
      + speed and timing of delivery
      + confrmation or acknowledgement requirement
*** [3.1.5] Network protocol requirements
    - in addition to indentifying source and destinatio, computer network protocols also define the details of how a message is transmitted across a network.
    - network protocols include the following requirements like:
      + message encoding
      + message formatting and encapsulation
      + message size
      + message timing
      + message delivery options
*** [3.1.6] Message encoding
    - encoding is the process of converting indormation into another acceptable form (for transmission)
    - decoding is th reverse process (done to interpret the information)
    - encoding between hosts must be in an appropriate format for the medium
    - messages sent are converted to bits by the sending host then encoded into a pattern of voltages on copper wires, infared lights in optical fibers, or microwaves for wireless systems. Then the destination host receives and decodes the signals to interpret the message
    - Example:
      + message source -> encoder -> transmitter -> transmission media -> receiver -> decoder -> message destination
*** [3.1.7] Message formatting and encapsulation
    - a message must use a specific format or structure
    - formats depend on the type of message and the channel that is used to deliver the message
